version: 2.1
jobs:
  build:
    working_directory: ~/ckeditor5/packages/ckeditor5-build-balloon-block
    docker:
      - image: circleci/node:14
    steps:
      - checkout

      - restore_cache:
          keys:
            - ckeditor5-{{ .Branch }}-{{ checksum "package.json" }}
            - ckeditor5-{{ .Branch }}-
            - ckeditor5-

      - run: echo //npm-proxy.fury.io/dialogue/:_authToken=$NPM_TOKEN >> ~/.npmrc

      - run: npm ci

      - save_cache:
          key: ckeditor5-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm

#      - run: npm run lint

      # - run: npm run test -- --coverage

#      - run: npm run build

      - deploy:
          name: Publish to NPM
          command: |
            if [[ $CIRCLE_TAG ]]; then
              npm pack | { read file_name; curl -F "package=@$file_name" "https://$NPM_TOKEN@push.fury.io/dialogue/"; }
            fi
workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - gemfury-upload
