version: 2.1

orbs:
  node: dialogue/node@1.0.0

aliases:
  - &executor
    executor:
      name: node/node
      version: "14.21.3"

workflows:
  release:
    jobs:
      - node/publish_package:
          name: 🚀 publish
          working_directory: ~/project/packages/ckeditor5-build-balloon-block
          build_command: ""  
          release_command: ""  
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          <<: *executor
          context: library-publisher
