version: 2.1
jobs:
  publish:
    working_directory: ~/ckeditor5/packages/ckeditor5-build-balloon-block
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: echo //npm-proxy.fury.io/dialogue/:_authToken=$GEMFURY_TOKEN >> ~/.npmrc
      - run:  npm publish --registry https://$GEMFURY_TOKEN@push.fury.io/dialogue/

workflows:
  build:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
          context:
            - gemfury-upload
